networks:
  meli:

services:
  postgres:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      - POSTGRES_USER=slbenitezd
      - POSTGRES_PASSWORD=b4ckendChallenge
      - POSTGRES_DB=meli_db
    healthcheck:
      test: ["CMD-SHELL", 'pg_is_read']
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./dataset/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - meli

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@meli.com
      PGADMIN_DEFAULT_PASSWORD: b4ckendChallenge
    depends_on:
      - postgres
    networks:
      - meli